#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("bandview.Resource", IsApplication=true)]

namespace bandview
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int heartbeat_anim = 2131034112;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int sensor_descriptions = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int sensor_icons = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int sensor_names = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int item_touch_helper_swipe_escape_velocity = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accelerometer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ambient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ambient_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int barometer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int calories = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int distance = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gsr = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gyro = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int heartrate = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pedometer = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rr = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int temp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int uv = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int beats = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int command = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int heart = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int level = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int levelImg = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int progressBar = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int raw_data = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int selector = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int sensorContainer = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int sensorDesc = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int sensorIcon = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int sensorList = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int sensorName = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int statusText = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AmbientLight = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HeartRate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int RawSensor = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SensorView = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int band = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7f090009
			public const int command_heartrate_acquiring = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int command_heartrate_locked = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int command_light = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int status_connected = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int status_connecting = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int status_failed = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int status_noimpl = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int status_notfound = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int status_searching = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int status_waiting = 2131296263;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
